CS/Models/Employee.cs
using System.Collections.Generic;

namespace TagBoxWithCustomTags.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public List<Role> Roles { get; set; }
        // ... another Employee's data fields.
    }
}

CS/Models/EmployeeViewModel.cs
using System.Collections.Generic;
using DevExpress.AspNetCore.Bootstrap;

namespace TagBoxWithCustomTags.Models
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }

        // Selected TagBox' values (both predefined and custom). 
        public BootstrapTagBoxValues<int> Roles { get; set; }
        public IEnumerable<Role> AllRoles { get; set; }
    }
}

CS/Models/Role.cs
namespace TagBoxWithCustomTags.Models
{
    public class Role
    {
        public int Id { get; set; }
        public string Text { get; set; }
    }
}

CS/Controllers/EditController.cs
using System.Collections.Generic;
using System.Linq;
using DevExpress.AspNetCore.Bootstrap;
using Microsoft.AspNetCore.Mvc;
using TagBoxWithCustomTags.Models;

namespace TagBoxWithCustomTags.Controllers
{
    public class EditController : Controller
    {
        public IActionResult Employee(int employeeID)
        {
            // Getting an Employee from database;
            Employee employeeDataObject = DataContext.GetEmployees(HttpContext)
                .First(e => e.Id == employeeID);

            // Create and fill a view model with data obtained from database.
            EmployeeViewModel model = new EmployeeViewModel()
            {
                Id = employeeDataObject.Id,
                Roles = new BootstrapTagBoxValues<int>()
                {
                    TagValues = employeeDataObject.Roles
                        .Select(r => r.Id).ToList()
                }
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Employee(EmployeeViewModel employee)
        {
            // Getting custom tags(custom roles) filled into a TagBox control
            List<string> newCustomRoles = employee.Roles.CustomTagTexts;

            if (DataContext.ValidateAndStoreNewRoles(newCustomRoles, HttpContext, out List<Role> newRoles))
            {
                // Getting selected predefined tag's ids
                List<int> selectedPredefinedRolesIds = employee.Roles.TagValues;

                List<Role> employeeRoles = DataContext.GetRoles(HttpContext)
                    .Where(r => selectedPredefinedRolesIds.Contains(r.Id)).ToList();
                employeeRoles.AddRange(newRoles);

                Employee employeeDataObject = DataContext.GetEmployees(HttpContext)
                    .First(e => e.Id == employee.Id);
                employeeDataObject.Roles = employeeRoles;

                DataContext.UpdateEmployee(employeeDataObject, HttpContext);
                TempData["Success"] = $"The Employee #{ employee.Id } has been updated";
                return RedirectToAction("Index", "Home");
            }

            TempData["Error"] = "Some roles are incorrect. Please fix them and submit a form again.";
            return View(employee);
        }
    }
}

CS/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace TagBoxWithCustomTags.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View(DataContext.GetEmployees(HttpContext));
        }
    }
}

CS/Views/Edit/Employee.cshtml
@model EmployeeViewModel

<h2>Employee #@Model.Id</h2>
<form method="post">
    @(Html.DevExpress()
        .BootstrapTagBoxFor(m => m.Roles)
        .Caption("Role")
        .AllowCustomTags(true)
        .ValueField("ID")
        .TextField("Text")
        .Bind(DataContext.GetRoles(Context)))

    @Html.HiddenFor(m => m.Id)
    <br />
    <button type="submit" class="btn btn-outline-success">Save</button>
    <a href='@Url.Action("Index", "Home")' class="btn btn-outline-secondary">Cancel</a>
</form>

CS/Views/Home/Index.cshtml
@model IEnumerable<Employee>
<h1>Employees</h1>
<ul class="list-group">
@foreach(var employee in Model) {
    <li class="list-group-item clearfix">
        <span class="float-left">
            <b>Employee #@employee.Id</b><br/>
            Roles: 
            @foreach(var role in employee.Roles) {
                <span class="badge badge-info">@role.Text</span>
            }
        </span>
        <span class="float-right">
            <a href='@Url.Action("Employee", "Edit", new { employeeID = @employee.Id })' class="btn btn-outline-primary">Edit</a>
        </span>
    </li>
}
</ul>

CS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DevExpress Bootstrap ASP.NET Core Tagbox With Custom Tags Example</title>
    <link rel="stylesheet" href="~/lib/css/bootstrap/bootstrap.css" />
    @Html.DevExpress().StyleSheets()
</head>
<body>
    <nav class="navbar mb-4 navbar-expand-md navbar-dark bg-dark">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand">
            DevExpress Bootstrap ASP.NET Core
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="container">
        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger">
                @TempData["Error"]
            </div>
        }
        @if(TempData["Success"] != null)
        {
            <div class="alert alert-success" role="alert">
                @TempData["Success"]
            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>Copyright &copy; 2006-@DateTime.Now.Year - Developer Express Inc</p>
        </footer>
    </div>

    <script src="~/lib/js/jquery/jquery.js"></script>
    @Html.DevExpress().Scripts()
</body>
</html>